# Generated by Django 5.2.17 on 2026-10-06 12:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='medicines.medicinecategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generic_name', models.CharField(db_index=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('strength', models.CharField(blank=True, help_text='e.g. "500 mg", "10 mg/5 ml"', max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('topical', 'Topical'), ('sublingual', 'Sublingual'), ('intravenous', 'Intravenous'), ('intramuscular', 'Intramuscular'), ('subcutaneous', 'Subcutaneous'), ('inhalation', 'Inhalation'), ('ophthalmic', 'Ophthalmic'), ('otic', 'Otic'), ('nasal', 'Nasal'), ('rectal', 'Rectal'), ('vaginal', 'Vaginal'), ('other', 'Other')], default='oral', max_length=30)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('gtin', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='GTIN')),
                ('description', models.TextField(blank=True)),
                ('prescription_required', models.BooleanField(default=False)),
                ('storage_condition', models.CharField(choices=[('room_temperature', 'Room Temperature'), ('cool', 'Cool (2-8 °C)'), ('cold', 'Cold (2-8 °C)'), ('frozen', 'Frozen (-20 °C)'), ('dry', 'Dry'), ('protect_from_light', 'Protect From Light')], default='room_temperature', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('dosage_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='medicines.dosageform')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.manufacturer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='medicines.medicinecategory')),
            ],
            options={
                'ordering': ['generic_name', 'brand_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(db_index=True)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('expired', 'Expired'), ('recalled', 'Recalled'), ('damaged', 'Damaged')], db_index=True, default='available', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_batches', to='branches.branch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='medicines.medicine')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_batches', to='branches.warehouse')),
            ],
            options={
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['branch', 'expiry_date'], name='batch_branch_expiry_idx'), models.Index(fields=['medicine', 'status'], name='batch_medicine_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'medicine', 'batch_number'), name='uniq_batch_per_branch_medicine'), models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='batch_purchase_price_non_negative'), models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='batch_selling_price_non_negative'), models.CheckConstraint(condition=models.Q(('manufacture_date__isnull', True), ('manufacture_date__lte', models.F('expiry_date')), _connector='OR'), name='batch_manufacture_before_expiry')],
            },
        ),
        migrations.AddConstraint(
            model_name='medicinecategory',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='uniq_category_name_parent'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['generic_name', 'brand_name'], name='medicine_name_idx'),
        ),
    ]
