# Generated by Django 5.2.17 on 2026-10-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('reserved', 'Reserved'), ('expired', 'Expired'), ('recalled', 'Recalled'), ('damaged', 'Damaged')], db_index=True, default='available', max_length=20),
        ),
    ]
