# Generated by Django 5.2.17 on 2026-10-07 11:02

import django.db.models.deletion
from django.db import migrations, models


def assign_medicine_tenants(apps, schema_editor):
    Medicine = apps.get_model("medicines", "Medicine")
    MedicineBatch = apps.get_model("medicines", "MedicineBatch")
    tenant_by_medicine = {}
    for batch in MedicineBatch.objects.select_related("branch").iterator():
        tenant_by_medicine.setdefault(batch.medicine_id, set()).add(
            batch.branch.pharmacy_id
        )
    for medicine_id, pharmacy_ids in tenant_by_medicine.items():
        if len(pharmacy_ids) == 1:
            Medicine.objects.filter(pk=medicine_id).update(
                pharmacy_id=next(iter(pharmacy_ids))
            )


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicine_reorder_level_alter_medicinebatch_status'),
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosageform',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(blank=True, help_text='Null only for a shared formulary entry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacies.pharmacy'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='gtin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='GTIN'),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='medicines.medicine'),
        ),
        migrations.RunPython(assign_medicine_tenants, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'barcode'), name='uniq_medicine_pharmacy_barcode'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'gtin'), name='uniq_medicine_pharmacy_gtin'),
        ),
    ]
