# Generated by Django 5.2.17 on 2026-10-07 08:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('receipt', 'Stock receipt (purchase)'), ('dispatch', 'Stock dispatch (sale)'), ('transfer', 'Internal transfer between branches'), ('adjustment', 'Manual adjustment'), ('return', 'Customer/supplier return')], db_index=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='medicines.medicinebatch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicines.medicine')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='branches.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch', '-created_at'], name='txn_batch_latest_idx')],
            },
        ),
    ]
