# Generated by Django 5.2.17 on 2026-10-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='direction',
            field=models.CharField(choices=[('in', 'Stock in'), ('out', 'Stock out')], default='in', max_length=3),
        ),
    ]
