# Generated by Django 5.2.17 on 2026-10-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('medicines', '0003_dosageform_is_active_manufacturer_is_active_and_more'),
        ('transactions', '0002_inventorytransaction_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='medicines.medicinebatch'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('sale_return', 'Sale return'), ('purchase_return', 'Purchase return'), ('adjustment_in', 'Adjustment in'), ('adjustment_out', 'Adjustment out'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('damage', 'Damaged stock'), ('expired', 'Expired stock'), ('receipt', 'Stock receipt (purchase)'), ('dispatch', 'Stock dispatch (sale)'), ('transfer', 'Internal transfer between branches'), ('adjustment', 'Manual adjustment'), ('return', 'Customer/supplier return')], db_index=True, max_length=20),
        ),
    ]
