# Generated by Django 5.2.17 on 2026-10-07 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('legal_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('account_bank', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='PK', max_length=2)),
                ('payment_terms_days', models.PositiveIntegerField(default=7)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='pharmacies.pharmacy')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'pharmacy'], name='supplier_name_pharmacy_idx')],
            },
        ),
    ]
